export { default as Dashboard } from "./dashboard/Dashboard";
export { default as FetchDetails } from "./dashboard/FetchDetails";
export { default as TenantInfoForm } from "./tenantInfoForm/TenantInfoForm";
export { default as FileConfigMain } from "./file-configs/FileConfigMain";
export { default as TenantSteps } from "./tenantSteps/TenantSteps";
export { default as ThemeGenerator } from "./themeGenerator/ThemeGenerator";
export { default as IconGenerator } from "./iconGenerator/IconGenerator";
export { default as FontsUpload } from "./fontsUpload/FontsUpload";
export { default as Login } from "./authentication/login/Login";
