// icons/index.ts
import {
  ArrowsClockwiseIcon,
  BellIcon,
  CheckCircleIcon,
  ListIcon,
  MagnifyingGlassIcon,
  PencilLineIcon,
  PlusIcon,
  TrashIcon,
} from "@phosphor-icons/react";

export const ReactIcons = {
  Bell: BellIcon,
  Menu: ListIcon,
  Search: MagnifyingGlassIcon,
  Refresh: ArrowsClockwiseIcon,
  TickCircle: CheckCircleIcon,
  // Setting: IoSettingsOutline,
  // ArrowDown: IoIosArrowDown,
  // Home: FiHome,
  // Dot: LuDot,
  // Dashboard: MdOutlineSpaceDashboard,
  // Clipboard: LuClipboardList,
  Plus: PlusIcon,
  Edit: PencilLineIcon,
  Delete: TrashIcon,
  // List: IoList,
  // Filter: FiFilter,
  // ArrowLeft: FaArrowLeft,
  // Text: RxText,
  // Email: HiOutlineMail,
  // Phone: HiOutlinePhone,
  // Link: IoLinkOutline,
  // MultiChoice: LuListOrdered,
  // Checkbox: IoMdCheckboxOutline,
  // Switch: IoMdSwitch,
  // Hash: LuHash,
  // Calendar: FiCalendar,
  // Star: FiStar,
  // FileUpload: LuFileUp,
  // OpenEye: FaRegEye,
  // CloseEye: FaRegEyeSlash,
  // Save: LuSave,
  // Drag: MdDragIndicator,
  // Branch: LuGitBranch,
  // More: RiMore2Fill,
  // Undo: LuUndo2,
  // Warning: IoWarning,
};
