import type { Metadata } from "next";
import "./globals.css";
import { Quicksand } from "next/font/google";
import { Header, Sidebar } from "@/components/templates";
import ClientProvider from "./providers/ClientProvider";

// Import the Quicksand font from Next.js
const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className} flex flex-col bg-background h-screen`}
      >
        <ClientProvider>
          <main className="flex gap-5 px-5 xl:px-8 ">
            <Sidebar />
            <div className="grow">
              <Header />
              <div className="flex flex-col grow p-5 bg-surface rounded-2xl">
                {children}
              </div>
            </div>
          </main>
        </ClientProvider>
      </body>
    </html>
  );
}
