import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import ClientProvider from "./providers/ClientProvider";

// Import the Quicksand font from Next.js
const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className} flex flex-col bg-background h-screen`}
      >
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
